### ISSUE TITLE
Update Homepage with Filler

### ISSUE THREAD

**Issue by peter-biz** [PNW-CS-Club/Club-Website#20]
Add Titles and temporary text boxes to the homepage where content should be displayed in the future.

**Comment by naguib-med** [comment]
Hello ! Can you assign me to this issue?

**Comment by AndrewNguyenITVN** [comment]
hi bro, I am interested your project, let me try on this problem. Can you assign it to me?

**Comment by mariontamnai** [comment]
Hey, I'm interested in your project. I can try to help with the issue
